version: "2"
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/<%=username%>/<%=project%>-web
    environment:
      - VIRTUAL_HOST=<%=project%>.guten.me
      - EXPOSE=80
      - LETSENCRYPT_HOST=<%=project%>.guten.me
      - LETSENCRYPT_EMAIL=ywzhaifei@gmail.com
    volumes:
      - ./uploads:/app/uploads
    links:
      - server
    restart: always

  server:
    image: registry.cn-hangzhou.aliyuncs.com/<%=username%>/<%=project%>-server
    volumes:
      - ./rc.js:/app/src/rc.js
      - ./uploads:/app/uploads
    links:
      - db
    restart: always

  db:
    image: postgres
    volumes:
      - ./latest.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "app"
      POSTGRES_INITDB_ARGS: ""
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    restart: always

networks:
  default:
    external:
      name: appsnet
