#!/usr/bin/env bash

main() {
  npm start
}

link() {
  yarn link gureact
}

unlink() {
  yarn unlink gureact
  yarn
}

case "$1" in
  '' ) main ;;
  deploy ) ../ake "$@" ;;
  b | build ) npm run build ;;
  t | test ) npm test ;;
  design ) gureact start-design ;;
  link ) link ;;
  unlink ) unlink ;;
  analyze ) source-map-explorer build/static/js/main.*.{js,map} ;;
esac
