#!/usr/bin/env bash

export PORT=4001
export WS_PORT=4002
export DATABASE_URL=${DATABASE_URL-postgres://localhost/<%=project%>}
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="src:$NODE_PATH"
export APP_ENV="node" # for gudatagen

main() {
  nodemon --exec babel-node src/server.js
}

seeds-dev() {
  babel-node scripts/seeds-dev.js
}

test() {
  jest --watch
}

coverage() {
  jest --coverage
}

link() {
  mkdir -p node_modules
  (cd node_modules && ln -s ../guserver/packages/* .)
}

build-docs() {
  mkdir -p build.docs
  babel-node scripts/gen-schema-text.js
  graphdoc -s ./build.docs/admin.graphql -o build.docs/admin
  graphdoc -s ./build.docs/store.graphql -o build.docs/store
}

case "$1" in
  "" ) main ;;
  deploy ) ../ake "$@" ;;
  seeds-dev ) seeds-dev ;;
  t | test ) test ;;
  coverage ) converage ;;
  link ) link ;;
  build:docs ) build-docs ;;
esac
