#!/usr/bin/env bash

export PORT=4001
export WS_PORT=4002
export DATABASE_URL=${DATABASE_URL-postgres://localhost/erp}
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="src:$NODE_PATH"
export APP_ENV="node" # for gudatagen

main() {
  nodemon --exec babel-node src/server.js
}

seeds-dev() {
  babel-node scripts/seeds-dev.js
}

test() {
  jest --watch
}

coverage() {
  jest --coverage
}

case "$1" in
  "" ) main ;;
  deploy ) ../ake "$@" ;;
  seeds-dev ) seeds-dev ;;
  t | test ) test ;;
  coverage ) converage ;;
esac
