#!/usr/bin/env bash

export PORT=4001
export WS_PORT=4002
export DATABASE_URL=${DATABASE_URL-postgres://localhost/<%=project%>}
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="src:$NODE_PATH"
export APP_ENV="node" # for gudatagen

main() {
  nodemon --exec babel-node src/server.js
}

link() {
  yarn link guserver guserver-auth-magic guserver-schema-mini guserver-process-upload
  rm -rf ~/dev/one/guserver/node_modules/graphql && ln -s `pwd`/node_modules/graphql ~/dev/one/guserver/node_modules 

  (cd uploads/processed && ln -sf ../../../shared/fixtures/images/* .)
  #ln -s ../../../shared/fixtures/images/post0.jpg uploads/processed/post0@thumb.jpg
}

unlink() {
  yarn unlink guserver guserver-auth-magic guserver-schema-mini guserver-process-upload
  yarn
}

case "$1" in
  "" ) main ;;
  t | test ) jest --watch ;
  build:docs ) guserver build-docs admin store ;;
  seeds-dev ) guserver seeds-dev ;;
  deploy ) ../ake "$@" ;;
  link ) link ;;
  unlink ) unlink ;;
esac
