#!/usr/bin/env bash

export PORT=4000
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="node_modules:$NODE_PATH" # for design mode with symlinked gureact needs react-scripts/webpack.config.dev

main() {
  react-app-rewired start
}

link() {
  yarn link gureact
}

unlink() {
  yarn unlink gureact
  yarn add gureact
}

fix() {
  sed 's/row: object/row: any/g' -i node_modules/@types/react-table/index.d.ts
}

case "$1" in
  '' ) main ;;
  push ) ../ake "$@" ;;
  b | build ) npm run build ;;
  t | test ) npm test ;;
  design ) gureact start-design ;;
  design-gen-data ) design-gen-data ;; 
  link ) link ;;
  unlink ) unlink ;;
  analyze ) source-map-explorer build/static/js/main.*.{js,map} ;;
  docs ) styleguidist server ;;
  lint ) eslint --ext .ts,.tsx . ;;
  fix ) fix ;;
  * ) echo 'Unkown command' ;;
esac
