#!/usr/bin/env bash

export PORT=4002
export DATABASE_URL=${DATABASE_URL-postgres://localhost/<%=project%>}
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="src:$NODE_PATH"
export APP_ENV="node" # for gudatagen
ts_node="ts-node --files --type-check"
typeorm="$ts_node ./node_modules/.bin/typeorm"

main() {
  nodemon --exec $ts_node src/server.ts
}

dump() {
  pg_dump --schema-only erp > docs/latest.sql
  sed -i 's/guten/root/g' docs/latest.sql
  echo "> docs/latest.sql"
  $ts_node scripts/dump-graphql-schema.ts docs/latest.graphql
  echo "> docs/latest.graphql"
}

case "$1" in
  "" ) main ;;
  t | test ) jest ;;
  test:watch ) DATABASE_URL="postgres://localhost/<%=project%>test" jest --watch ;;  # NODE_ENV=test is set by jest
  test:e2e ) DABASE_URL="postgres://localhost/<%=project%>test" jest --config jestE2e.config.js ;;
  test:e2e:debug ) DEBUG=1 DABASE_URL="postgres://localhost/<%=project%>test" jest --config jestE2e.config.js ;;
  test:setup ) psql -c 'CREATE DATABASE <%=project%>test' ;;
  test:fixtures ) $ts_node src/shared/fixtures/fixtures.ts ;;
  db:setup ) psql -c 'CREATE DATABASE <%=project%>'; $typeorm schema:sync ;;
  db:seeds-dev ) $ts_node scripts/seeds-dev.ts ./src/fixtures/seeds.dev.ts ;;
  db:reset ) $typeorm schema:drop; $typeorm schema:sync ;; 
  db:sql) psql <%=project%> ;;
  build:docs ) guserver build-docs admin store ;;
  push ) ../ake "$@" ;;
  dump ) dump ;;
  ts-node ) shift; $ts_node "$@" ;;
  typeorm ) shift; $typeorm "$@" ;;
esac
