#!/usr/bin/env bash

# ./ake deploy web server
# ./ake deploy all

deploy() {
  [[ $1 == "all" ]] && names="web server" || names="$@"
  for name in $names; do
    git push origin master:$name
  done
}

case "$1" in
  deploy ) shift; deploy "$@" ;;
esac
