#!/usr/bin/env bash

# ./ake push web server
# ./ake push all

push() {
  [[ $1 == "all" ]] && names="web server" || names="$@"
  for name in $names; do
    git push origin master:$name
  done
}

case "$1" in
  push ) shift; push "$@" ;;
esac
