stages:
  - image
  - deploy
  - docs
  - mirror
variables:
  GIT_SSL_NO_VERIFY: "1"

server:
  stage: image
  only:
    - master
  script:
    - cd server
    - cp -r ../shared src/shared
    - build-image <%=username%>/<%=project%>-server
  image: gutenye/docker

web:
  stage: image
  only:
    - master
  script:
    - cd web
    - build-image <%=username%>/<%=project%>-web
  image: gutenye/docker

deploy:
  stage: deploy
  only:
    - master
  script:
    - deploy <%=project%> 23
  image: gutenye/deploy

pages:  
  stage: docs
  script:
    - cd web
    - yarn
    - yarn run build:docs
    - mv build.docs ../public/web
    - cd -

    - cd server
    - yarn
    - yarn run build:docs
    - mv build.docs ../public/server
    - cd -
  artifacts:
    paths:
      - public
    expire_in: 1h
  only:
    - master
  image: gutenye/node

mirror:
  stage: mirror
  only:
    - master
  script:
    - git-push git@gitlab.com:<%=username%>/<%=project%>.git
  image: ilyasemenov/gitlab-ci-git-push
