#!/usr/bin/env bash

export PORT=4002
export DATABASE_URL=${DATABASE_URL-postgres://guten:guten@localhost/<%=project%>}
export PATH="node_modules/.bin:$PATH"
export NODE_PATH="src:$NODE_PATH"
export APP_ENV="node" # for gudatagen

main() {
  nodemon --exec ts-node --files --type-check src/server.ts
}

typeorm() {
  ts-node --files --type-check ./node_modules/.bin/typeorm "$@"
}

case "$1" in
  "" ) main ;;
  test ) jest ;;
  test:watch ) jest --watch ;;
  test:e2e ) jest --config jest-e2e.config.js ;;
  test:model ) ts-node --files --type-check src/testmodel.ts ;;
  test:fixtures ) ts-node --files src/shared/fixtures/fixtures.ts ;;
  seeds:dev ) ts-node --files scripts/seeds-dev.ts ./src/seeds.dev.ts ;;
  build:docs ) guserver build-docs admin store ;;
  push ) ../ake "$@" ;;
  typeorm ) shift; typeorm "$@" ;;
  dump ) pg_dump erp > docs/latest.sql ;;
esac
